# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0005_auto_20161125_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowchart',
            name='by2',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='審核'),
        ),
        migrations.AlterField(
            model_name='flowchart',
            name='by3',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='批准'),
        ),
        migrations.AlterField(
            model_name='flowchartprocess',
            name='a',
            field=models.IntegerField(blank=True, null=True, verbose_name='序號'),
        ),
    ]
