# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flowchartprocess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField(blank=True, null=True, verbose_name='序號')),
                ('b', models.CharField(default='.', max_length=32, verbose_name='部門')),
                ('c', models.CharField(max_length=32, verbose_name='工序')),
            ],
        ),
    ]
