# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0002_auto_20161128_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='標記'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(default='.', max_length=256, verbose_name='主題記要'),
        ),
    ]
