# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0005_auto_20161129_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date',
            new_name='date1',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='followup',
            new_name='fix',
        ),
        migrations.AddField(
            model_name='note',
            name='date2',
            field=models.DateField(blank=True, null=True, verbose_name='日期'),
        ),
    ]
