# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0006_auto_20161129_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowchart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=32, verbose_name='品名')),
                ('c1', models.CharField(default='.', max_length=32, verbose_name='模號')),
                ('c2', models.CharField(default='.', max_length=32, verbose_name='模穴')),
                ('e1', models.CharField(default='.', max_length=32, verbose_name='圖面版本')),
                ('e2', models.CharField(default='.', max_length=32, verbose_name='表面等級')),
                ('g1', models.CharField(default='.', max_length=32, verbose_name='版序')),
                ('g2', models.CharField(default='.', max_length=32, verbose_name='材質')),
                ('by1', models.CharField(default='.', max_length=32, verbose_name='編制')),
                ('by1date', models.DateField(blank=True, null=True, verbose_name='編制日期')),
                ('by2', models.CharField(blank=True, max_length=32, null=True, verbose_name='審核')),
                ('by2date', models.DateField(blank=True, null=True, verbose_name='審核日期')),
                ('by3', models.CharField(blank=True, max_length=32, null=True, verbose_name='批准')),
                ('by3date', models.DateField(blank=True, null=True, verbose_name='批准日期')),
                ('cust_name', models.CharField(max_length=32, verbose_name='客戶名稱')),
            ],
            options={
                'verbose_name': '生產工藝流程卡',
                'verbose_name_plural': '生產工藝流程卡',
            },
        ),
        migrations.CreateModel(
            name='Flowchartprocess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField(blank=True, null=True, verbose_name='序號')),
                ('b', models.CharField(default='.', max_length=32, verbose_name='部門')),
                ('c', models.CharField(max_length=32, verbose_name='工序')),
                ('d', models.CharField(max_length=128, verbose_name='過程描述')),
                ('e', models.CharField(default='.', max_length=256, verbose_name='品質要求')),
                ('f', models.CharField(blank=True, max_length=32, null=True, verbose_name='設備')),
                ('g', models.CharField(blank=True, max_length=32, null=True, verbose_name='刀、治、模具')),
                ('h', models.CharField(blank=True, max_length=32, null=True, verbose_name='檢具')),
                ('flowchart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectnote.Flowchart')),
            ],
            options={
                'verbose_name': '流程',
                'verbose_name_plural': '流程',
            },
        ),
        migrations.AlterField(
            model_name='note',
            name='date1',
            field=models.DateField(blank=True, null=True, verbose_name='問題日期'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date2',
            field=models.DateField(blank=True, null=True, verbose_name='解決日期'),
        ),
        migrations.AlterField(
            model_name='note',
            name='fix',
            field=models.CharField(default='.', max_length=512, verbose_name='解決概要'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(default='.', max_length=512, verbose_name='問題描述'),
        ),
        migrations.AlterField(
            model_name='note',
            name='where',
            field=models.CharField(default='.', max_length=512, verbose_name='問題位置'),
        ),
    ]
