# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0008_auto_20161201_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(default='.', max_length=32, verbose_name='工号')),
                ('b', models.CharField(default='.', max_length=32, verbose_name='姓名')),
                ('c', models.CharField(max_length=128, verbose_name='部门名称')),
                ('d', models.CharField(max_length=128, verbose_name='班组名称')),
                ('e', models.CharField(default='.', max_length=256, verbose_name='职位名称')),
                ('f', models.CharField(default='.', max_length=32, verbose_name='人员性质')),
            ],
            options={
                'verbose_name': '員工',
                'verbose_name_plural': '員工',
            },
        ),
        migrations.AlterField(
            model_name='smm',
            name='monthnum',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=12, verbose_name='月'),
        ),
    ]
