# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0009_auto_20161220_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.DateField(verbose_name='日期')),
                ('b', models.CharField(default='.', max_length=32, verbose_name='产品代码')),
                ('f', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='重量')),
            ],
            options={
                'verbose_name': 'Transxxx',
                'verbose_name_plural': 'Transyyy',
            },
        ),
    ]
