# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0010_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans',
            name='c',
            field=models.CharField(default='.', max_length=32, verbose_name='产品品名'),
        ),
        migrations.AddField(
            model_name='trans',
            name='d',
            field=models.CharField(default='.', max_length=32, verbose_name='原料代码'),
        ),
        migrations.AddField(
            model_name='trans',
            name='e',
            field=models.CharField(default='.', max_length=32, verbose_name='原料品名'),
        ),
    ]
