# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0011_auto_20170207_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans',
            name='g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='trans',
            name='h',
            field=models.CharField(default='.', max_length=32, verbose_name='单据号码'),
        ),
        migrations.AddField(
            model_name='trans',
            name='i',
            field=models.CharField(default='.', max_length=32, verbose_name='备注+'),
        ),
    ]
