# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0012_auto_20170207_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trans',
            options={'verbose_name': '原材料收发', 'verbose_name_plural': '原材料收发'},
        ),
        migrations.AddField(
            model_name='trans',
            name='yrmonth',
            field=models.CharField(choices=[('2017-01', '2017-01'), ('2017-02', '2017-02')], default='2017-01', max_length=7, verbose_name='年月'),
        ),
    ]
