# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0014_auto_20170207_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='cat',
            field=models.CharField(choices=[('期初', '期初'), ('购进', '购进'), ('领用', '领用')], default='购进', max_length=2, verbose_name='类型'),
        ),
    ]
