# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0015_auto_20170207_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yrmonth', models.CharField(choices=[('2017-01', '2017-01'), ('2017-02', '2017-02'), ('2017-03', '2017-03'), ('2017-04', '2017-04'), ('2017-05', '2017-05'), ('2017-06', '2017-06'), ('2017-07', '2017-07'), ('2017-08', '2017-08'), ('2017-09', '2017-09'), ('2017-10', '2017-10'), ('2017-11', '2017-11'), ('2017-12', '2017-12')], default='2017-01', max_length=7, verbose_name='年月')),
                ('a', models.CharField(default='.', max_length=32, verbose_name='原料代码')),
                ('b', models.CharField(default='.', max_length=32, verbose_name='原料品名')),
                ('e', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='期初')),
                ('g', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='购进')),
                ('i', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='领用')),
                ('k', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='结存')),
            ],
            options={
                'verbose_name_plural': '原材料收发',
                'verbose_name': '原材料收发',
            },
        ),
    ]
