# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0016_rpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rpt',
            options={'verbose_name': '原材料收发统计表', 'verbose_name_plural': '原材料收发统计表'},
        ),
    ]
