# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0017_auto_20170208_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='流程编号')),
                ('ver', models.CharField(max_length=8, verbose_name='版本')),
                ('ver_date', models.DateField(verbose_name='修订日期')),
                ('title', models.CharField(max_length=200)),
                ('dept', models.CharField(max_length=16, verbose_name='负责单位')),
                ('editor', models.CharField(max_length=16, verbose_name='修改人员')),
                ('page_num', models.CharField(max_length=16, verbose_name='页次')),
                ('intro', models.CharField(max_length=200, verbose_name='流程定义')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活躍')),
                ('diagram', models.CharField(default='mark002.svg', max_length=200, verbose_name='流程图')),
            ],
        ),
        migrations.CreateModel(
            name='Sopitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_seq', models.IntegerField(default=0)),
                ('item_text', models.CharField(max_length=600)),
                ('sop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectnote.Sop')),
            ],
        ),
    ]
