# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0018_sop_sopitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sop',
            options={'verbose_name': 'SOP ', 'verbose_name_plural': 'SOP '},
        ),
        migrations.RemoveField(
            model_name='sop',
            name='diagram',
        ),
    ]
