# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0020_sop_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop',
            name='is_bpm',
            field=models.BooleanField(default=False, verbose_name='是否BPM'),
        ),
    ]
