# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0021_sop_is_bpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=16, verbose_name='部門')),
                ('order_seq', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sop',
            name='dept2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectnote.Dept'),
        ),
    ]
