# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0023_auto_20170302_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sopdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=16, verbose_name='分類')),
                ('seq', models.IntegerField(default=0, verbose_name='序號')),
                ('sys', models.CharField(max_length=16, verbose_name='sys')),
                ('procedure', models.CharField(max_length=16, verbose_name='procedure')),
            ],
        ),
    ]
