# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0024_sopdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopdata',
            name='by_default',
            field=models.CharField(max_length=64, null=True, verbose_name='建议负责人员'),
        ),
        migrations.AddField(
            model_name='sopdata',
            name='deadline',
            field=models.DateField(null=True, verbose_name='应完成日期'),
        ),
        migrations.AddField(
            model_name='sopdata',
            name='files',
            field=models.CharField(max_length=255, null=True, verbose_name='档案代号'),
        ),
        migrations.AddField(
            model_name='sopdata',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='必要'),
        ),
        migrations.AddField(
            model_name='sopdata',
            name='method',
            field=models.CharField(max_length=16, null=True, verbose_name='建置方式'),
        ),
        migrations.AddField(
            model_name='sopdata',
            name='notes',
            field=models.CharField(max_length=255, null=True, verbose_name='注意事项'),
        ),
        migrations.AddField(
            model_name='sopdata',
            name='program',
            field=models.CharField(max_length=16, null=True, verbose_name='程序'),
        ),
        migrations.AddField(
            model_name='sopdata',
            name='recommend',
            field=models.CharField(max_length=255, null=True, verbose_name='建议'),
        ),
        migrations.AddField(
            model_name='sopdata',
            name='remarks',
            field=models.CharField(max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='sopdata',
            name='responsible',
            field=models.CharField(max_length=64, null=True, verbose_name='负责人员'),
        ),
        migrations.AddField(
            model_name='sopdata',
            name='supporter',
            field=models.CharField(max_length=64, null=True, verbose_name='来源单位、支持单位'),
        ),
        migrations.AlterField(
            model_name='sopdata',
            name='procedure',
            field=models.CharField(max_length=16, verbose_name='作业'),
        ),
        migrations.AlterField(
            model_name='sopdata',
            name='sys',
            field=models.CharField(max_length=16, verbose_name='系统'),
        ),
    ]
