# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0026_auto_20170303_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='T100',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='運行程序')),
                ('name', models.CharField(max_length=64, verbose_name='運行程序名稱')),
                ('sop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectnote.Sop')),
            ],
        ),
    ]
