# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0028_t100item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='演練代碼')),
                ('name', models.CharField(max_length=64, verbose_name='演練名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Drilstep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=0)),
                ('note', models.CharField(max_length=512, verbose_name='筆記')),
                ('drill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectnote.Drill')),
            ],
        ),
        migrations.CreateModel(
            name='Prog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='運行程序')),
                ('name', models.CharField(max_length=64, verbose_name='運行程序名稱')),
            ],
        ),
        migrations.AddField(
            model_name='drilstep',
            name='prog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectnote.Prog'),
        ),
    ]
