# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0029_auto_20170310_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drilstep',
            new_name='Drillstep',
        ),
    ]
