# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0032_drillstep_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailywork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empe_name', models.CharField(max_length=16, verbose_name='姓名')),
                ('work_date', models.DateField(verbose_name='日期')),
                ('work_brief', models.CharField(max_length=512, verbose_name='工作要點')),
                ('work_desc', models.CharField(max_length=512, verbose_name='工作內容')),
                ('remarks', models.CharField(max_length=512, verbose_name='備註')),
            ],
            options={
                'verbose_name': '每人每日工作記要',
                'verbose_name_plural': '每人每日工作記要',
            },
        ),
        migrations.AlterModelOptions(
            name='drillstep',
            options={'ordering': ('drill', 'seq')},
        ),
    ]
