# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0034_auto_20170320_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bpm',
            options={'ordering': ('dept_name', 'sop_name')},
        ),
        migrations.AddField(
            model_name='bpm',
            name='bpm_type',
            field=models.CharField(default='.', max_length=512, verbose_name='单据类型'),
        ),
    ]
