# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0035_auto_20170320_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpm',
            name='dev_by',
            field=models.CharField(default='.', max_length=512, verbose_name='建议开发人员'),
        ),
    ]
