# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0036_bpm_dev_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpm',
            name='item_seq',
            field=models.IntegerField(default=0, verbose_name='预估实施工时（h）'),
        ),
    ]
