# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0037_bpm_item_seq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bpm',
            old_name='item_seq',
            new_name='man_hr',
        ),
    ]
