# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0038_auto_20170320_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpm',
            name='form_name',
            field=models.CharField(default='.', max_length=512, verbose_name='表单名称'),
        ),
        migrations.AddField(
            model_name='bpm',
            name='process_name',
            field=models.CharField(default='.', max_length=512, verbose_name='流程名称'),
        ),
        migrations.AddField(
            model_name='bpm',
            name='step1_by',
            field=models.CharField(default='.', max_length=512, verbose_name='UI'),
        ),
        migrations.AddField(
            model_name='bpm',
            name='step2_by',
            field=models.CharField(default='.', max_length=512, verbose_name='JS'),
        ),
        migrations.AddField(
            model_name='bpm',
            name='step3_by',
            field=models.CharField(default='.', max_length=512, verbose_name='流程外形'),
        ),
        migrations.AddField(
            model_name='bpm',
            name='step4_by',
            field=models.CharField(default='.', max_length=512, verbose_name='流程代码'),
        ),
    ]
