# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0039_auto_20170320_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpm',
            name='complete_date',
            field=models.DateField(null=True, verbose_name='行情日期'),
        ),
    ]
