# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0040_bpm_complete_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpm',
            name='complete_date',
        ),
    ]
