# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0042_auto_20170320_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpm',
            name='wait_t100',
            field=models.CharField(default='.', max_length=512, verbose_name='需待T100客制'),
        ),
        migrations.AlterField(
            model_name='bpm',
            name='to_print',
            field=models.CharField(default='.', max_length=512, verbose_name='打印需求'),
        ),
    ]
