# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0044_auto_20170321_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj', models.CharField(default='monitor001', max_length=512, verbose_name='項目')),
                ('seq', models.IntegerField(default=0, verbose_name='序號')),
                ('sql', models.CharField(max_length=512, verbose_name='SQL語句')),
                ('lbl_en', models.CharField(default='.', max_length=512, verbose_name='Label英文')),
                ('lbl_zh', models.CharField(default='.', max_length=512, verbose_name='Label中文')),
                ('remarks', models.CharField(default='...', max_length=512, verbose_name='備註')),
            ],
            options={
                'ordering': ('prj', 'seq'),
            },
        ),
    ]
