# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0045_sqlstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlstatement',
            name='title',
            field=models.CharField(default='.', max_length=512, verbose_name='標題'),
        ),
        migrations.AlterField(
            model_name='sqlstatement',
            name='sql',
            field=models.CharField(default='.', max_length=512, verbose_name='SQL語句'),
        ),
    ]
