# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0046_auto_20170406_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlstatement',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是'),
        ),
    ]
