# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0047_sqlstatement_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlstatement',
            name='lbl_en',
        ),
        migrations.RemoveField(
            model_name='sqlstatement',
            name='lbl_zh',
        ),
        migrations.AddField(
            model_name='sqlstatement',
            name='lbl',
            field=models.CharField(blank=True, default='.', max_length=512, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='sqlstatement',
            name='vname',
            field=models.CharField(blank=True, default='.', max_length=512, null=True, verbose_name='View Name'),
        ),
        migrations.AlterField(
            model_name='sqlstatement',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否活躍'),
        ),
        migrations.AlterField(
            model_name='sqlstatement',
            name='sql',
            field=models.CharField(blank=True, default='.', max_length=512, null=True, verbose_name='SQL語句'),
        ),
    ]
