# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0048_auto_20170406_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlstatement',
            name='prog',
            field=models.CharField(blank=True, default='.', max_length=512, null=True, verbose_name='運行程序'),
        ),
        migrations.AddField(
            model_name='sqlstatement',
            name='vcode',
            field=models.CharField(blank=True, default='.', max_length=512, null=True, verbose_name='View定義'),
        ),
    ]
