# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0050_auto_20170511_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='T100Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(default='.', max_length=32, verbose_name='项次')),
                ('b', models.CharField(default='.', max_length=32, verbose_name='提报时间')),
                ('c', models.CharField(default='.', max_length=32, verbose_name='富鈦提报人')),
                ('d', models.CharField(default='.', max_length=32, verbose_name='问题类型')),
                ('f', models.CharField(max_length=512, verbose_name='问题点')),
            ],
            options={
                'verbose_name': 'T100问题处理进度追踪',
                'verbose_name_plural': 'T100问题处理进度追踪',
            },
        ),
    ]
