# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0051_t100todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='t100todo',
            name='e',
            field=models.CharField(default='.', max_length=32, verbose_name='鼎捷责任人'),
        ),
    ]
