# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0052_t100todo_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='t100todo',
            name='i',
            field=models.CharField(default='.', max_length=512, verbose_name='顾问回复处理结果'),
        ),
        migrations.AddField(
            model_name='t100todo',
            name='j',
            field=models.CharField(default='.', max_length=512, verbose_name='验证结果'),
        ),
        migrations.AddField(
            model_name='t100todo',
            name='k',
            field=models.CharField(default='.', max_length=32, verbose_name='计划完成日期'),
        ),
        migrations.AddField(
            model_name='t100todo',
            name='l',
            field=models.CharField(default='.', max_length=32, verbose_name='实际完成日期'),
        ),
        migrations.AddField(
            model_name='t100todo',
            name='m',
            field=models.CharField(default='.', max_length=32, verbose_name='用户确认'),
        ),
        migrations.AlterField(
            model_name='t100todo',
            name='f',
            field=models.CharField(default='.', max_length=512, verbose_name='问题点'),
        ),
    ]
