# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0053_auto_20170527_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t100todo',
            name='a',
            field=models.IntegerField(default='.', max_length=32, verbose_name='项次'),
        ),
    ]
