# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0054_auto_20170527_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t100todo',
            name='b',
            field=models.DateField(blank=True, max_length=32, null=True, verbose_name='提报时间'),
        ),
    ]
