# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0055_auto_20170527_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t100todo',
            name='k',
            field=models.DateField(blank=True, max_length=32, null=True, verbose_name='计划完成日期'),
        ),
        migrations.AlterField(
            model_name='t100todo',
            name='l',
            field=models.DateField(blank=True, max_length=32, null=True, verbose_name='实际完成日期'),
        ),
    ]
