# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0056_auto_20170527_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='t100todo',
            name='g',
            field=models.CharField(default='.', max_length=512, verbose_name='问题点示例'),
        ),
        migrations.AddField(
            model_name='t100todo',
            name='h',
            field=models.CharField(default='.', max_length=512, verbose_name='讨论结果'),
        ),
    ]
