# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0057_auto_20170527_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='T100Todo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField(default='.', max_length=32, verbose_name='项次')),
                ('b', models.DateField(blank=True, max_length=32, null=True, verbose_name='提报日期')),
                ('c', models.CharField(default='.', max_length=32, verbose_name='提报人员')),
                ('d', models.CharField(default='.', max_length=32, verbose_name='鼎捷责任人')),
                ('e', models.CharField(default='.', max_length=32, verbose_name='需求类型')),
                ('f', models.CharField(default='.', max_length=512, verbose_name='需求')),
                ('g', models.CharField(default='.', max_length=512, verbose_name='表单格式打包')),
                ('h', models.CharField(default='.', max_length=512, verbose_name='讨论结果')),
                ('i', models.CharField(default='.', max_length=512, verbose_name='顾问回复处理结果')),
                ('j', models.CharField(default='.', max_length=512, verbose_name='计划需求确认完成日期')),
                ('k', models.DateField(blank=True, max_length=32, null=True, verbose_name='计划开发完成日期')),
                ('l', models.DateField(blank=True, max_length=32, null=True, verbose_name='实际完成日期')),
                ('m', models.CharField(default='.', max_length=32, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '各部门需求处理进度追踪',
                'verbose_name': '各部门需求处理进度追踪',
            },
        ),
        migrations.CreateModel(
            name='TrackT100',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField(default='.', max_length=32, verbose_name='序号')),
                ('b', models.DateField(blank=True, max_length=32, null=True, verbose_name='提报时间')),
                ('c', models.CharField(default='.', max_length=32, verbose_name='提报人员')),
                ('d', models.CharField(default='.', max_length=32, verbose_name='鼎捷责任人')),
                ('e', models.CharField(default='.', max_length=32, verbose_name='问题分类')),
                ('f', models.CharField(default='.', max_length=512, verbose_name='问题描述')),
                ('g', models.CharField(default='.', max_length=512, verbose_name='问题分析')),
                ('h', models.CharField(default='.', max_length=512, verbose_name='解决方案')),
                ('i', models.CharField(blank=True, max_length=32, null=True, verbose_name='计划完成时间')),
                ('j', models.CharField(blank=True, max_length=32, null=True, verbose_name='实际完成时间')),
                ('k', models.DateField(default='.', max_length=512, verbose_name='进度状态')),
                ('l', models.DateField(default='.', max_length=512, verbose_name='用户确认')),
                ('m', models.CharField(default='.', max_length=32, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '全制程--T100问题追踪表',
                'verbose_name': '全制程--T100问题追踪表',
            },
        ),
    ]
