# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0058_t100todo2_trackt100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackt100',
            name='a',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
    ]
