# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0059_auto_20170623_0832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T100Todo2',
        ),
    ]
