# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0060_delete_t100todo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t100todo',
            name='a',
            field=models.IntegerField(default=0, verbose_name='项次'),
        ),
    ]
