# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0061_auto_20170623_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackt100',
            name='i',
            field=models.DateField(blank=True, max_length=32, null=True, verbose_name='计划完成时间'),
        ),
        migrations.AlterField(
            model_name='trackt100',
            name='j',
            field=models.DateField(blank=True, max_length=32, null=True, verbose_name='实际完成时间'),
        ),
        migrations.AlterField(
            model_name='trackt100',
            name='k',
            field=models.CharField(default='.', max_length=512, verbose_name='进度状态'),
        ),
        migrations.AlterField(
            model_name='trackt100',
            name='l',
            field=models.CharField(default='.', max_length=512, verbose_name='用户确认'),
        ),
    ]
