# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0064_trackt100report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackt100report',
            name='m',
            field=models.CharField(default='备注', max_length=512, verbose_name='备注'),
        ),
    ]
