# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-27 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0067_trackreport00'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackreport00',
            name='deptId',
            field=models.CharField(default='0000', max_length=16, verbose_name='DEPT_ID'),
        ),
    ]
