# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-27 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0068_trackreport00_deptid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackreport00',
            name='h',
            field=models.CharField(default='.', max_length=512, verbose_name='盤點現況'),
        ),
    ]
