# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-27 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0069_auto_20170627_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='T100Dept',
            fields=[
                ('deptId', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='DEPT_ID')),
                ('deptName', models.CharField(default='.', max_length=16, verbose_name='DEPT')),
            ],
        ),
    ]
