# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-27 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0070_t100dept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T100Dept',
        ),
        migrations.AlterField(
            model_name='trackreport00',
            name='d',
            field=models.CharField(default='.', max_length=512, verbose_name='业务需求'),
        ),
        migrations.AlterField(
            model_name='trackreport00',
            name='e',
            field=models.CharField(default='.', max_length=512, verbose_name='讨论结果'),
        ),
    ]
