# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0073_auto_20170628_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='t100dept',
            name='D0',
            field=models.IntegerField(default=0, verbose_name='总笔数'),
        ),
    ]
