# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0075_trackreport00_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackreport00',
            name='status',
            field=models.IntegerField(choices=[(0, '---'), (1, '鼎捷開發未开工'), (2, '鼎捷開發在制'), (3, '鼎捷開發完成待验收'), (4, '鼎捷開發完成已验收'), (5, '鼎捷開發取消'), (6, '鼎捷開發状态不明')], default=0, verbose_name='6/28清点'),
        ),
    ]
