# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-29 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0076_auto_20170628_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackreport00',
            name='easy_level',
            field=models.IntegerField(choices=[(0, '(未定)'), (1, '低'), (2, '中低'), (3, '中'), (4, '中高'), (5, '高')], default=0, verbose_name='難易度'),
        ),
        migrations.AddField(
            model_name='trackreport00',
            name='rpt_type',
            field=models.IntegerField(choices=[(0, '(未定)'), (10, 'T100程式功能調整'), (20, '單據打印'), (30, '清單式報表'), (40, '統計分析類報表')], default=0, verbose_name='客製分類'),
        ),
        migrations.AlterField(
            model_name='trackreport00',
            name='status',
            field=models.IntegerField(choices=[(0, '(未定)'), (1, '鼎捷開發未开工'), (2, '鼎捷開發在制'), (3, '鼎捷開發完成待验收'), (4, '鼎捷開發完成已验收'), (5, '鼎捷開發取消'), (6, '鼎捷開發状态不明')], default=0, verbose_name='6/28清点'),
        ),
    ]
