# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-29 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnote', '0077_auto_20170629_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackreport00',
            name='rpt_type',
            field=models.IntegerField(choices=[(0, '(未定)'), (10, 'T100程式功能調整'), (20, '單據打印'), (30, '清單式報表'), (40, '統計分析類報表'), (50, 'BPM')], default=0, verbose_name='客製分類'),
        ),
    ]
