# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0062_item011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item012',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f01', models.CharField(default='.', max_length=99, verbose_name='生产订单号')),
                ('f02', models.CharField(default='.', max_length=99, verbose_name='物料代码')),
                ('f03', models.CharField(default='.', max_length=99, verbose_name='物料说明')),
                ('f04', models.CharField(default='.', max_length=99, verbose_name='机台吨位')),
                ('f05', models.CharField(default='.', max_length=99, verbose_name='材质')),
                ('f06', models.FloatField(default=0, verbose_name='工时定额(分钟）')),
                ('f07', models.IntegerField(default=0, verbose_name='模穴')),
                ('f08', models.IntegerField(default=0, verbose_name='订单数量')),
                ('f09', models.IntegerField(default=0, verbose_name='已生产数量')),
                ('f10', models.IntegerField(default=0, verbose_name='未生产数量')),
                ('f11', models.FloatField(default=0, verbose_name='合计工时(小时）')),
                ('f12', models.DateField(verbose_name='下单日期')),
                ('f13', models.CharField(default='.', max_length=99, verbose_name='压铸交货日期')),
                ('f14', models.CharField(default='.', max_length=99, verbose_name='责任生管')),
            ],
        ),
    ]
