# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0063_item012'),
    ]

    operations = [
        migrations.CreateModel(
            name='T01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f02', models.CharField(max_length=30, verbose_name='B')),
                ('f03', models.CharField(max_length=30, verbose_name='C')),
                ('f04', models.CharField(max_length=30, verbose_name='D')),
            ],
        ),
    ]
