# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0065_flowchart_flowchartprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowchartprocess',
            name='f',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='設備'),
        ),
        migrations.AlterField(
            model_name='flowchartprocess',
            name='g',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='刀、治、模具'),
        ),
        migrations.AlterField(
            model_name='flowchartprocess',
            name='h',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='檢具'),
        ),
    ]
