# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0066_auto_20161128_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T01',
        ),
    ]
