# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否活躍'),
        ),
    ]
