# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170208_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeback_text', models.CharField(default='.', max_length=200, verbose_name='回覆')),
                ('username', models.CharField(default='.', max_length=200, verbose_name='用戶名')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
