# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170208_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='remark',
            field=models.CharField(default='..', max_length=200, verbose_name='Remark'),
        ),
    ]
