# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_choice_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('choice_text', models.IntegerField(default=0)),
                ('debug', models.CharField(default='..', max_length=200, verbose_name='Remark')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
