# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_choice2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice2',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice2',
        ),
    ]
