# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20170209_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feeback_text',
            field=models.CharField(default='.', max_length=200, verbose_name='回覆'),
        ),
    ]
