# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_feedback_feeback_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='question',
            field=models.CharField(default='.', max_length=200, verbose_name='Question'),
        ),
    ]
