# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_feedback_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feeback_text',
            new_name='feedback',
        ),
    ]
