# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_sop_sopitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop',
            name='diagram',
            field=models.ImageField(null=True, upload_to='', verbose_name='流程图'),
        ),
    ]
