# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_sop_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sop',
            name='diagram',
            field=models.CharField(default='mark002.svg', max_length=200, verbose_name='流程图'),
        ),
    ]
